import { template } from 'meteor/templating';
import './main.html';
import '../imports/ui/header.js';
import '../imports/ui/welcome.js';
import '../imports/ui/config.js';
import '../imports/ui/config2.js';
import '../imports/ui/config3.js';
import '../imports/ui/home.js';
import '../imports/ui/body.js';
import '../imports/css/bootstrap-grid.min.css';
import '../imports/css/bootstrap-reboot.min.css';
import '../imports/css/bootstrap.min.css';
import '../imports/css/style.css';
import '../imports/js/js.js';
import '../imports/js/funcs.html';