import { template } from 'meteor/templating';
import './main.html';
import '../imports/ui/header.js';
import '../imports/ui/welcome.js';
import '../imports/ui/config.js';
import '../imports/ui/cinfig2.js';
import '../imports/ui/home.js';
import '../imports/ui/body.js';
import '../imports/js/js.js';
import '../imports/js/funcs.html';